# Internationalization
spring:
  messages:
    basename: messages/messages
  profiles:
    # default, map or spring-data profiles
    active: spring-data
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: admin
